name: Validate

on:
  push:
    branches:
      - '**'

jobs:
  validate:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./tests
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Lint and test
        run: make validate
